version: '3.7'

services: 
  # api
  url-shortener-api: 
    container_name: url-shortener
    build: ./
    command: npm start
    working_dir: /usr/src/url-shortener
    environment: 
      REDIS_URI: redis://redis:6379
    links: 
      - redis
    ports: 
      - "1235:1235"
    volumes: 
      - ./:/usr/src/url-shortener

  # redis db
  redis: 
    image: redis
    ports: 
      - "6379:6379"