version: '3.7'

services: 
  url-shortener-api: 
    container_name: url-shortener
    build: ./
    command: npm start
    working_dir: /usr/src/url-shortener
    ports: 
      - "1235:1235"
    volumes: 
      - ./:/usr/src/url-shortener